### ISSUE TITLE
can't compile for apple M-2 chip

### ISSUE THREAD

**Issue by ellensn** [lennartverhagen/k-Wave-CPUGPU-macOS#1]
I posted in the k-wave forum (sorry for the spam!) but I don't seem to have enough technical ability to get the make file modified to support the Apple M-2 chip architecture.

The error I get:

`clang: error: the clang compiler does not support '-march=native'`

I'm using the clang g++ compiler (`CXX = g++`) with openmp (`OPENMP = -Xpreprocessor -fopenmp -lomp`):
```
clang --version returns:
Apple clang version 14.0.0 (clang-1400.0.29.202)
Target: arm64-apple-darwin22.3.0
Thread model: posix
InstalledDir: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin
```

**Comment by elma16** [comment]
Hello, I've been in the same position of trying to get this to work, until I found [this](https://github.com/waltsims/k-wave-omp-darwin). I've tested this makefile on my m1 machine, and it worked fine (except for a few warnings, but this is probably just my incompetence).

**Comment by ellensn** [comment]
Thanks for following up! I ended up giving up (for this and a few other, related items) and bought a PC.
